package com.infy.dto;

import com.infy.entity.Novel;

import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Pattern;

public class NovelDTO {
	// @NotNull
	// @Min(1)

	// @Null(message = "Id should not be provided") /// since it will be
	// autogenerated when we create a new Novel in the db, it should not be
	// provided by the user
	private Integer id;

	@NotEmpty
	@Pattern(regexp = "[A-Za-z][A-Za-z ]*", message = "{novel.title.isalphabetic}")
	private String title;

	private Integer year;

	private Integer authId; // ADD ONLY IF YOU WANT TO GO FROM NOVEL TO AUTHOR ManyToOne
							// in this project our aim is to go from Author to novel

	public NovelDTO() {
	};

	public NovelDTO(Integer id, String title, Integer year, Integer authId) {
		this.id = id;
		this.title = title;
		this.year = year;
		this.authId = authId;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Integer getAuthId() {
		return authId;
	}

	public void setAuthId(Integer authId) {
		this.authId = authId;
	}

	@Override
	public String toString() {
		return "NovelDTO [id=" + id + ", title=" + title + ", year=" + year + ", authId=" + authId + "]";
	}

	static public NovelDTO from(Novel entity) {
		return new NovelDTO(entity.getId(), entity.getTitle(), entity.getYear(), entity.getAuthId());
	}

}
