package com.infy.service;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import jakarta.transaction.Transactional;

import org.springframework.stereotype.Service;

import com.infy.dto.AuthorDTO;
import com.infy.dto.NovelDTO;
import com.infy.entity.Author;
import com.infy.entity.Novel;
import com.infy.repository.AuthorRepository;
import com.infy.repository.NovelRepository;

@Service
@Transactional
public class AuthorServiceImpl implements AuthorService {
	public AuthorServiceImpl(AuthorRepository authorRepository, NovelRepository novelRepository) {
        this.authorRepository = authorRepository;
        this.novelRepository = novelRepository;
    }
	
	private final AuthorRepository authorRepository;
	private final NovelRepository novelRepository;
	
	private Author putNovelsInAuthor(Author author, AuthorDTO authorDTO) {
		if (authorDTO.getNovelDTOs()!=null) {
			List<Novel> novels = authorDTO.getNovelDTOs().stream()
					.map(Novel::from).collect(Collectors.toList());
			author.setNovels(novels);
		}
		return author;
	}

	private AuthorDTO putNovelsInAuthorDTO(AuthorDTO authorDTO, Author author) {
		List<Novel> novelList = author.getNovels();
		if (novelList!=null) {
			List<NovelDTO> novelDTOList = novelList.stream()
					.map(NovelDTO::from)
					.collect(Collectors.toList());
			authorDTO.setNovelDTOs(novelDTOList);
		}
		return authorDTO;
	}
	
	
	@Override
	public AuthorDTO addAuthor(AuthorDTO authorDTO) throws Exception {
		if (authorRepository.findById(authorDTO.getId()).isPresent())
			throw new Exception("Author Already Present");
		Author author = putNovelsInAuthor(Author.from(authorDTO), authorDTO);
		author.setNovels(null);  // null to begin with
		List<Novel> novels= new ArrayList<Novel>();
		if (authorDTO.getNovelDTOs()!=null) {
			authorDTO.getNovelDTOs().forEach(novelDTO->{
				Novel novel = Novel.from(novelDTO);
				novelRepository.save(novel);  /// this generates the primary key
				novels.add(novel);
			});
			author.setNovels(novels);
		}
		
		authorRepository.save(author);
		// Since the novels are newly created with new IDs autogenerated. We will copy new Novel DTOs 
		// before returning
		// after .save, the author entity has novel entities which have their IDs set
		List<NovelDTO> novelDTOs = novels.stream().map(novel -> NovelDTO.from(novel))
				.collect(Collectors.toList());
		authorDTO.setNovelDTOs(novelDTOs);
		return authorDTO;
	}

	@Override
	public List<NovelDTO> getNovelsByAuthorName(String authorName) {
		 return authorRepository.findByName(authorName).getNovels().stream().map(novel->NovelDTO.from(novel))
		 .collect(Collectors.toList());
	}

	@Override
	public List<NovelDTO> getNovelsByNameAndYear(String name, Integer year) {
		return authorRepository.findByName(name).getNovels().stream()
				.filter(novel -> novel.getYear().equals(year))
				.map(novel -> NovelDTO.from(novel))
				.collect(Collectors.toList());
	}
	@Override
	public List<AuthorDTO> allAuthors() {
		List<AuthorDTO> authorDTOList = new ArrayList<AuthorDTO>();
		authorRepository.findAll().forEach(author->authorDTOList.add(putNovelsInAuthorDTO(AuthorDTO.from(author), author)));
		return authorDTOList;
	}
	@Override
	public AuthorDTO deleteAuthor(Integer authorId) throws Exception {
		AuthorDTO authorDTO = putNovelsInAuthorDTO(AuthorDTO.from(authorRepository.findById(authorId).orElseThrow(()->new Exception("Bad Author Id"))), null);
		authorRepository.deleteById(authorId);
		return authorDTO;
	}

	@Override
	public AuthorDTO updateAuthor(Integer authorId, String authorName) throws Exception {
		Author author = authorRepository.findById(authorId).orElseThrow(()->new Exception("Bad Author Id"));
		author.setName(authorName);
		return putNovelsInAuthorDTO(AuthorDTO.from(author), author);
	}

}
