package com.infy.service;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import jakarta.transaction.Transactional;

import org.springframework.stereotype.Service;

import com.infy.dto.AuthorDTO;
import com.infy.dto.NovelDTO;
import com.infy.entity.Author;
import com.infy.entity.Novel;
import com.infy.repository.AuthorRepository;
import com.infy.repository.NovelRepository;

@Service
@Transactional
public class AuthorServiceImpl implements AuthorService {
	public AuthorServiceImpl(AuthorRepository authorRepository, NovelRepository novelRepository) {
        this.authorRepository = authorRepository;
        this.novelRepository = novelRepository;
    }
	
	private final AuthorRepository authorRepository;
	private final NovelRepository novelRepository;
	
	private Author authorFrom(AuthorDTO authorDTO) {
		Author author = new Author();
		author.setId(authorDTO.getId());
		author.setName(authorDTO.getName());
		if (authorDTO.getNovelDTOs()!=null) {
			List<Novel> novels = authorDTO.getNovelDTOs().stream()
					.map(novelDTO -> novelFrom(novelDTO)).collect(Collectors.toList());
			author.setNovels(novels);
		}
		return author;
	}

	private Novel novelFrom(NovelDTO novelDTO) {
		Novel novel = new Novel();
		novel.setId(novelDTO.getId());
		novel.setTitle(novelDTO.getTitle());
		novel.setYear(novelDTO.getYear());
		novel.setAuthId(novelDTO.getAuthId());
		/// NOT GOING TO ADD A NEW AUTHOR, so fetch from DB
		return novel;
	}
	
	private NovelDTO novelDTOFrom(Novel novel) {
		NovelDTO novelDTO = new NovelDTO();
		novelDTO.setId(novel.getId());
		novelDTO.setTitle(novel.getTitle());
		novelDTO.setYear(novel.getYear());
		novelDTO.setAuthId(novel.getAuthId());
		return novelDTO;
	}
	
	private AuthorDTO authorDTOFrom(Author author) {
		AuthorDTO authorDTO = new AuthorDTO();
		authorDTO.setId(author.getId());
		authorDTO.setName(author.getName());
		List<Novel> novelList = author.getNovels();
		if (novelList!=null) {
			List<NovelDTO> novelDTOList = novelList.stream()
					.map(novel -> novelDTOFrom(novel))
					.collect(Collectors.toList());
			authorDTO.setNovelDTOs(novelDTOList);
		}
		return authorDTO;
	}
	
	
	@Override
	public AuthorDTO addAuthor(AuthorDTO authorDTO) throws Exception {
		if (authorRepository.findById(authorDTO.getId()).isPresent())
			throw new Exception("Author Already Present");
		Author author = authorFrom(authorDTO);
		author.setNovels(null);  // null to begin with
		List<Novel> novels= new ArrayList<Novel>();
		if (authorDTO.getNovelDTOs()!=null) {
			authorDTO.getNovelDTOs().forEach(novelDTO->{
				Novel novel = novelFrom(novelDTO);
				novelRepository.save(novel);  /// this generates the primary key
				novels.add(novel);
			});
			author.setNovels(novels);
		}
		
		authorRepository.save(author);
		// Since the novels are newly created with new IDs autogenerated. We will copy new Novel DTOs 
		// before returning
		// after .save, the author entity has novel entities which have their IDs set
		List<NovelDTO> novelDTOs = novels.stream().map(novel -> novelDTOFrom(novel))
				.collect(Collectors.toList());
		authorDTO.setNovelDTOs(novelDTOs);
		return authorDTO;
	}

	@Override
	public List<NovelDTO> getNovelsByAuthorName(String authorName) {
		 return authorRepository.findByName(authorName).getNovels().stream().map(novel->novelDTOFrom(novel))
		 .collect(Collectors.toList());
	}

	@Override
	public List<NovelDTO> getNovelsByNameAndYear(String name, Integer year) {
		return authorRepository.findByName(name).getNovels().stream()
				.filter(novel -> novel.getYear().equals(year))
				.map(novel -> novelDTOFrom(novel))
				.collect(Collectors.toList());
	}

	@Override
	public List<AuthorDTO> allAuthors() {
		List<AuthorDTO> authorDTOList = new ArrayList<AuthorDTO>();
		authorRepository.findAll().forEach(author->authorDTOList.add(authorDTOFrom(author)));
		return authorDTOList;
	}

	@Override
	public NovelDTO addNovel(NovelDTO novelDTO) throws Exception {  // assume that they send the Author ID in there
		Novel novel =  novelFrom(novelDTO);
		novel.setId(null);
		return novelDTOFrom(novelRepository.save(novel));
	}

	@Override
	public NovelDTO updateNovel(NovelDTO novelDTO) throws Exception {
		Novel novel = novelRepository.findById(novelDTO.getId()).orElseThrow(()->new Exception("No Novel for Id"));
		novel.setAuthId(novelDTO.getAuthId());
		novel.setTitle(novelDTO.getTitle());
		novel.setYear(novelDTO.getYear());
		return novelDTOFrom(novel); 
	}

	@Override
	public NovelDTO deleteNovel(Integer novelId) throws Exception {
		NovelDTO novelDTO = novelDTOFrom(novelRepository.findById(novelId).orElseThrow(()->new Exception("Bad novel ID"))) ;
		novelRepository.deleteById(novelId);
		return novelDTO;
	}

	@Override
	public AuthorDTO deleteAuthor(Integer authorId) throws Exception {
		AuthorDTO authorDTO = authorDTOFrom(authorRepository.findById(authorId).orElseThrow(()->new Exception("Bad Author Id")));
		authorRepository.deleteById(authorId);
		return authorDTO;
	}

	@Override
	public AuthorDTO updateAuthor(Integer authorId, String authorName) throws Exception {
		Author author = authorRepository.findById(authorId).orElseThrow(()->new Exception("Bad Author Id"));
		author.setName(authorName);
		return authorDTOFrom(author);
	}

}
